matplotlib:
  figure.figsize: [20, 12]
  figure.dpi: 300
  axes.grid: true
  axes.prop_cycle: ["1f77b4", "ff7f0e", "2ca02c", "d62728", "9467bd"]
  font.size: 11
  savefig.dpi: 300
  savefig.bbox: tight

seaborn:
  style: whitegrid
  palette: deep
  context: notebook

eda:
  plot_settings:
    default_figsize: [12, 8]
    font_size: 10
    style: 'default'
    palette: 'husl'

  display_limits:
    max_categories_for_plot: 20
    max_categories_for_countplot: 10
    max_categorical_features_to_plot: 6
    max_heatmap_columns: 20
    correlation_plot_columns: 3
    numeric_plot_columns: 3
    outlier_sample_size: 5000

  statistical_thresholds:
    high_cardinality_threshold: 50
    memory_warning_mb: 100
    missing_values_warning_pct: 50
    top_categories_display: 10

output:
  dir: ./figures
  formats: [png, pdf]
